language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules
script:
  - cd ./functions && npm install && cd ..
  - cd ./website && npm install
  - npm run lint
  - npm test
  - npm run build && cd ..
deploy:
  provider: firebase
  token:
    secure: Rx2xerfItobnZP3mMCSM6RGc4ENdQggWjaIk2xXmZN4eptqd2fsUPJ/5KVy8yEY6aMrks6VDEKbGYyGKZ3Mr5iyAE8Wkx08447KH43yEBcVuo1/l4wiQVdrIuSd5YVgfYBS20j0aKq0ppGFHevCRbYWgEFrzjcvpKTU9UDoK/XIpyxqdZnZ7HHqSGixr7DjjYLhNep+zn/RkhT4qVPbHDmZCIewAPawgw11e9qz2jTGd9O1gU14BsYIs8Rs3FWaBvX/vhRAaWqjo5MnbODBbyL6OyW6PNqPSme4q4qa2WqkHbseNxXyKYftxUgfFLGbM+c/UA5GE14lpk+F0Wi4medVTM4tyupQG/FD8PO23i+mq4tu8lZMDWgVvj7IYLVbT3D2rfdQsIeYlvVLrZiG36VxxVFieobB9kVkT3tOr3i2toHckn3/YEhsXoB6MW3qYRjN0lvjLdO2E1yUi7T95xSMEmqqyMDMF34qqoQRYndLUWoGF9xZ0UgegHfwezoIjqysKjZWTHCuSeTxLJKpFG68cJb7lZvURLYAnYEDJHRFFHFANlafh/6qDpndm77K4l3tCGL+ooteKqAVMAZFRUAT5RHY3cN1bvLacjDQBSIzCyQhfc9wf09B+F+O7r24UPvUZzxaGHJG7eH+9zNuL4fgez7/och3mtfVbwiID47s=
  skip_cleanup: true