language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage:
      - name: test
      if: type IN (pull_request)
      script:
        - cd ./functions && npm install && cd ..
        - cd ./website && npm install
        - npm run lint
        - npm test
    - stage:
      - name: build&deploy
      if: (branch = master) AND (type NOT IN (pull_request))
      script:
        - node travis.js
        - npm install -g firebase-tools
        - cd ./functions && npm install && cd ..
        - cd ./website && npm install
        - npm run build
        - firebase deploy --token $FIREBASE_TOKEN
