language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      script:
      if: branch != master
        - cd ./functions && npm install && cd ..
        - cd ./website && npm install
        - npm run lint
        - npm test
    - stage: build
      if: branch = master
      script:
        - cd ./website && npm run build
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  on:
    branch:
      - deploy