language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules
before_install:
  - npm install -g firebase-tools
jobs:
  include:
    - stage: test
      script:
        - cd ./functions && npm install && cd ..
        - cd ./website && npm install
        - npm run lint
        - npm test
    - stage: build
      script:
        - npm run build && cd ..
    - stage: deploy
      script:
        - firebase deploy --token $FIREBASE_TOKEN