language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules
jobs:s
  include:
    - stage: test
      script:
        - cd ./functions && npm install && cd ..
        - cd ./website && npm install
        - npm run lint
        - npm test
    - stage: build&deploy
      script:
      if: branch = master
        - npm install -g firebase-tools
        - cd ./functions && npm install && cd ..
        - cd ./website && npm install
        - npm run build
        - firebase deploy --only hosting --token $FIREBASE_TOKEN